# GitHub Labels Configuration
# This file defines all labels used in the repository
# Labels are automatically synced using GitHub Actions or can be created manually

# Quality Control Labels
- name: "spam"
  color: "D32F2F"
  description: "Spam PR - will be rejected"

- name: "invalid"
  color: "E65100"
  description: "Invalid contribution"

# Difficulty Labels
- name: "good first issue"
  color: "7057FF"
  description: "Good for newcomers and first-time contributors"

- name: "beginner friendly"
  color: "0E8A16"
  description: "Suitable for beginners"

- name: "intermediate"
  color: "FFA500"
  description: "Requires some experience"

- name: "advanced"
  color: "D73A4A"
  description: "Requires advanced knowledge"

# Type Labels
- name: "bug"
  color: "D73A4A"
  description: "Something isn't working"

- name: "feature"
  color: "A2EEEF"
  description: "New feature or request"

- name: "enhancement"
  color: "84B6EB"
  description: "Improvement to existing feature"

- name: "documentation"
  color: "0075CA"
  description: "Improvements or additions to documentation"

- name: "refactor"
  color: "FBCA04"
  description: "Code refactoring"

- name: "performance"
  color: "FF6B6B"
  description: "Performance improvements"

- name: "security"
  color: "B60205"
  description: "Security-related issues"

- name: "testing"
  color: "1D76DB"
  description: "Adding or improving tests"

- name: "dependencies"
  color: "0366D6"
  description: "Dependency updates"

- name: "ui/ux"
  color: "E99695"
  description: "User interface and experience improvements"

- name: "accessibility"
  color: "5319E7"
  description: "Accessibility improvements"

# Status Labels
- name: "needs-review"
  color: "FBCA04"
  description: "Awaiting review from maintainers"

- name: "in-progress"
  color: "0E8A16"
  description: "Work in progress"

- name: "blocked"
  color: "D93F0B"
  description: "Blocked by other issues or dependencies"

- name: "on-hold"
  color: "FEF2C0"
  description: "On hold for now"

- name: "ready-to-merge"
  color: "0E8A16"
  description: "Approved and ready to be merged"

- name: "needs-changes"
  color: "FBCA04"
  description: "Changes requested by reviewers"

# Priority Labels
- name: "priority: critical"
  color: "B60205"
  description: "Critical priority"

- name: "priority: high"
  color: "D93F0B"
  description: "High priority"

- name: "priority: medium"
  color: "FBCA04"
  description: "Medium priority"

- name: "priority: low"
  color: "0E8A16"
  description: "Low priority"

# Special Labels
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "question"
  color: "D876E3"
  description: "Further information is requested"

- name: "wontfix"
  color: "FFFFFF"
  description: "This will not be worked on"

- name: "duplicate"
  color: "CFD3D7"
  description: "This issue or pull request already exists"

- name: "stale"
  color: "EEEEEE"
  description: "No recent activity"

- name: "potential-spam"
  color: "FF9800"
  description: "Flagged for potential spam - under review"

# Area Labels
- name: "area: backend"
  color: "5319E7"
  description: "Backend-related changes"

- name: "area: frontend"
  color: "1D76DB"
  description: "Frontend-related changes"

- name: "area: database"
  color: "0E8A16"
  description: "Database-related changes"

- name: "area: api"
  color: "0075CA"
  description: "API-related changes"

- name: "area: devops"
  color: "D93F0B"
  description: "DevOps and infrastructure changes"

- name: "area: ci/cd"
  color: "FBCA04"
  description: "CI/CD pipeline changes"
